version: "3.9"

services:

    postgres:
        image: postgres:15.0-alpine
        container_name: postgres
        ports:
          - "5432:5432"
        volumes:
          - oauth-server-db:/var/lib/postgresql/data
        env_file:
          - ./.env
        restart: on-failure
        logging:
          options:
            max-size: 10m
            max-file: "3"
        networks:
          - oauth-server-net

    server:
      container_name: oauth2-server
      build: 
        context: ./server
      networks:
          - oauth-server-net
      ports:
        - 5000:5000
      env_file:
        - ./.env
      volumes:
        - ./server:/server
      # entrypoint: CompileDaemon --build="go build main.go" --command="./main standup"

networks:
  oauth-server-net:
    driver: bridge

volumes:
  oauth-server-db:
